language: python
dist: xenial
os:
  - linux

python:
  - '3.6'
  - '3.7'
  - 'pypy3.6-7.1.1'

env:
  - ''  # Run with default environment
  - PYTHONOPTIMIZE=1

cache:
  directories:
    - $HOME/.cache/pip

install:
  - ./scripts/setup.sh

script:
  - ./scripts/test.sh
  - ./scripts/benchmark.sh
