language: python
dist: xenial
os:
  - linux

python:
  - '3.6'
  - '3.7'

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -e .
  - pip install -r dev-requirements.txt

script:
  - ./scripts/test.sh
