language: python
dist: xenial
os:
  - linux

python:
  - '3.5'
  - '3.6'
  - '3.7'

env:
  - ''  # Run with default environment
  - PYTHONOPTIMIZE=1

cache:
  pip: true

install:
  - pip install -e .
  - pip install -r dev-requirements.txt

script:
  - ./scripts/test.sh
  - ./scripts/benchmark.sh
  - python setup.py build
