language: python
dist: xenial
os:
  - linux

python:
  - '3.5'
  - '3.6'
  - '3.7'

env:
  - ''  # Run with default environment
  - PYTHONOPTIMIZE=1

cache:
  directories:
    - $HOME/.cache/pypoetry

before_install:
  - pip install poetry

install:
  - ./scripts/setup.sh

script:
  - poetry run ./scripts/test.sh
  - poetry run ./scripts/benchmark.sh
  - poetry build 
