name: Benchmark

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('dev-requirements.txt') }}-${{ hashFiles('setup.py') }}
      - name: Install OpenCV
        run: sudo apt update && sudo apt install -y python3-opencv
      - name: Install dependencies
        run: bash ./scripts/setup.sh
      - name: Run benchmarks
        run: bash ./scripts/benchmark.sh
